using System.Text.RegularExpressions;

namespace Emberfield.Localization
{
    /// <summary>
    /// The game in Spanish (Spain). Screens compose their text in English; composed text is matched by
    /// templates. Text already written in Spanish passes through, apart from a few lines that still name
    /// English buildings or modes. Specific templates come before general ones.
    /// </summary>
    public static class SpanishCatalog
    {
        public static TextTranslator Create()
        {
            var t = new TextTranslator(GameLanguage.Spanish);
            Content(t); Rules(t); Commands(t); Factions(t); Research(t); Hud(t); Naval(t); Menus(t); Settings(t); Guide(t); Online(t); Store(t); Corrections(t);
            return t;
        }

        private static void P(TextTranslator t, params string[] pairs) { for (int i = 0; i + 1 < pairs.Length; i += 2) t.Add(pairs[i], pairs[i + 1]); }
        private static void T(TextTranslator t, params string[] pairs) { for (int i = 0; i + 1 < pairs.Length; i += 2) t.Template(pairs[i], pairs[i + 1]); }

        // Units, buildings, resources, eras, technologies, factions, biomes, cosmetics and enum names shown on screen.
        private static void Content(TextTranslator t)
        {
            P(t,
                "Tender", "Aldeano", "Tenders", "Aldeanos", "Reedguard", "Lancero", "Reedguards", "Lanceros",
                "Stringwarden", "Arquero", "Stringwardens", "Arqueros", "Strider", "Jinete", "Striders", "Jinetes",
                "Threadkeeper", "Enlace", "Ashrunner", "Corredor de ceniza", "Ashrunners", "Corredores de ceniza",
                "Supply Cart", "Carro de suministros", "Dune Elephant", "Elefante de las dunas", "Dune Elephants", "Elefantes de las dunas",
                "Frostguard", "Guardia de escarcha", "Frostguards", "Guardias de escarcha", "Sun Lion", "León solar", "Sun Lions", "Leones solares",
                "Grove Guardian", "Guardián de la arboleda", "Grove Guardians", "Guardianes de la arboleda",
                "War Troll", "Trol de guerra", "War Trolls", "Troles de guerra", "Ember Drake", "Draco de ascuas", "Ember Drakes", "Dracos de ascuas",
                "Camel Archer", "Arquero de camello", "Camel Archers", "Arqueros de camello", "Quilted Lancer", "Jinete acolchado", "Quilted Lancers", "Jinetes acolchados",
                "Siege Ram", "Ariete", "Siege Ladder", "Escalera de asedio", "Siege Tower", "Torre de asedio",
                "Hearth", "Hogar", "Hearths", "Hogares", "Shelter", "Casa", "Storeyard", "Almacén", "Muster Hall", "Cuartel",
                "Archive", "Archivo", "Supply Outpost", "Puesto de suministros", "Curtain Wall", "Muralla", "Fortress Gate", "Puerta fortificada",
                "Watchtower", "Atalaya", "Keep", "Fortaleza", "Beast Lodge", "Establo de bestias", "Siege Workshop", "Taller de asedio",
                "Orchard", "Huerto", "Copse", "Arboleda", "Metal seam", "Veta de metal", "Stone outcrop", "Afloramiento de piedra",
                "Food", "Comida", "Wood", "Madera", "Stone", "Piedra", "People", "Población",
                "Settlement", "Asentamiento", "Kingdom", "Reino", "Dominion", "Dominio", "Empire", "Imperio", "Conquest", "Conquista",
                "Surrender", "Rendición", "SimultaneousElimination", "Eliminación simultánea", "SimultaneousDominion", "Dominio simultáneo",
                "Easy", "Fácil", "Hard", "Difícil", "Easy rival", "Rival fácil", "Normal rival", "Rival normal", "Hard rival", "Rival difícil",
                "Loose", "Abierta", "Line", "En línea", "Box", "En bloque",
                "Worker", "Trabajador", "Infantry", "Infantería", "Cavalry", "Caballería", "Ranged", "A distancia", "Light", "Ligera",
                "Heavy", "Pesada", "Structure", "Estructura", "Creature", "Criatura", "Siege", "Asedio",
                "To resource", "Hacia el recurso", "Gathering", "Recolectando", "Delivering", "Entregando", "To construction", "Hacia la obra",
                "Constructing", "Construyendo", "Idle", "Inactivo", "Moving", "En marcha",
                "Packing", "Empaquetando", "Packed", "Empaquetado", "Deploying", "Desplegando", "Logistics", "Logística", "Muster", "Reclutamiento",
                "Temperate forest", "Bosque templado", "Forest", "Bosque", "Caribbean", "Caribe", "Desert", "Desierto",
                "River crossings, wooded approaches and fertile frontier valleys.", "Vados de río, accesos boscosos y fértiles valles fronterizos.",
                "Palm groves, sheltered coves and contested coastal passages.", "Palmerales, calas resguardadas y pasos costeros disputados.",
                "Oasis routes, sandstone ruins and open dune approaches.", "Rutas de oasis, ruinas de arenisca y accesos abiertos entre dunas.",
                "Lands of Legend", "Tierras de Leyenda", "Homelands", "Patrias",
                "Each army starts in its own land: elven forest, highland plains or volcanic wastes.", "Cada ejército empieza en su tierra: bosque élfico, llanuras de montaña o páramo volcánico.",
                "Miraj Sultanate", "Sultanato de Miraj", "Solar Kingdom", "Reino Solar", "Aven Compact", "Pacto de Aven", "Serevin March", "Marca de Serevin",
                "Skeld Clans", "Clanes de Skeld", "Verdant Covenant", "Alianza Verdeante", "Ashen Dominion", "Dominio Ceniciento", "Drakeforged Clans", "Clanes Forjadracos");

            P(t,
                "Advance to Kingdom", "Avanzar al Reino", "Advance to Dominion", "Avanzar al Dominio", "Advance to Empire", "Avanzar al Imperio",
                "Enter the Kingdom Era to unlock the Archive and first research tier.", "Entra en la era del Reino para desbloquear el Archivo y el primer nivel de investigación.",
                "Enter the Dominion Era. Requires a completed Archive.", "Entra en la era del Dominio. Requiere un Archivo terminado.",
                "Enter the Empire Era. Requires completed Work Rotation research.", "Entra en la era del Imperio. Requiere haber investigado Rotación de turnos.",
                "Better Handles", "Mangos mejorados", "Tenders gather one additional resource per work operation.", "Los Aldeanos recolectan un recurso más por ciclo de trabajo.",
                "Work Rotation", "Rotación de turnos", "Tenders gather one further resource per work operation.", "Los Aldeanos recolectan otro recurso más por ciclo de trabajo.",
                "Tempered Edges", "Filos templados",
                "Soldiers and creatures gain two attack damage before counters and armor. Siege engines are not affected.", "Soldados y criaturas ganan dos de daño antes de las bonificaciones y la armadura. No afecta a las máquinas de asedio.",
                "Measured Strikes", "Golpes medidos",
                "Soldiers and creatures gain two further attack damage before counters and armor. Siege engines are not affected.", "Soldados y criaturas ganan otros dos de daño antes de las bonificaciones y la armadura. No afecta a las máquinas de asedio.",
                "Layered Gear", "Equipo reforzado", "Military units gain one armor.", "Las unidades militares ganan un punto de armadura.",
                "Interlocked Plates", "Placas entrelazadas", "Military units gain one further armor.", "Las unidades militares ganan otro punto de armadura.",
                "Reciprocal Stores", "Almacenes recíprocos",
                "Chartered Storeyards gain two metres of coverage and Threadkeeper tether range; relay radius stays unchanged.", "Los Almacenes con cédula ganan dos metros de alcance y de enlace con los Enlaces; el radio del relevo no cambia.",
                "Prepared Encampments", "Campamentos preparados",
                "Supply Outposts pack and redeploy two seconds sooner; movement and exposure remain.", "Los Puestos de suministros se empaquetan y despliegan dos segundos antes; el trayecto y la exposición no cambian.",
                "Reinforced Howdahs", "Castilletes reforzados", "Dune Elephants gain two armor.", "Los Elefantes de las dunas ganan dos puntos de armadura.",
                "Oathsteel", "Acero juramentado", "Frostguards gain three attack damage.", "Los Guardias de escarcha ganan tres de daño.",
                "Solar Radiance", "Resplandor solar", "Sun Lions gain two armor.", "Los Leones solares ganan dos puntos de armadura.",
                "Living Heartwood", "Duramen vivo", "Grove Guardians gain two armor.", "Los Guardianes de la arboleda ganan dos puntos de armadura.",
                "Blood Pact", "Pacto de sangre", "War Trolls gain four attack damage.", "Los Troles de guerra ganan cuatro de daño.",
                "Runeforged Scales", "Escamas rúnicas", "Ember Drakes gain two armor.", "Los Dracos de ascuas ganan dos puntos de armadura.",
                "Composite Bows", "Arcos compuestos", "Camel Archers gain two attack damage.", "Los Arqueros de camello ganan dos de daño.",
                "Quilted Barding", "Bardas acolchadas", "Quilted Lancers gain two armor.", "Los Jinetes acolchados ganan dos puntos de armadura.");

            P(t,
                "Tenders carry one extra resource. Choose Storeyard logistics or muster charters, extended by Threadkeeper relays.",
                "Los Aldeanos cargan un recurso más. Elige cédulas de logística o de reclutamiento en el Almacén, ampliadas con relevos de Enlace.",
                "Cavalry move fifteen percent faster and Tenders carry one extra resource. Mobile outposts and Ashrunner repositioning reward flexible supply lines.",
                "La caballería se mueve un quince por ciento más rápido y los Aldeanos cargan un recurso más. Los puestos móviles y el reposicionamiento de los Corredores de ceniza premian las líneas de suministro flexibles.",
                "Caravans carry one extra resource. Slow, costly dune elephants break fortifications; spears and mobile archers punish them.",
                "Las caravanas cargan un recurso más. Los elefantes de las dunas, lentos y caros, derriban fortificaciones; las lanzas y los arqueros móviles los castigan.",
                "Infantry and cavalry gain one armor. Frostguards anchor costly shield formations; archers and superior economies can outmaneuver them.",
                "La infantería y la caballería ganan un punto de armadura. Los Guardias de escarcha sostienen caras formaciones de escudos; los arqueros y una economía superior pueden superarlos.",
                "Wounded armies recover two health per second near a Hearth or Keep after six peaceful seconds. Sun Lions lead swift charges; ranged focus defeats their limited numbers.",
                "Los ejércitos heridos recuperan dos de salud por segundo cerca de un Hogar o una Fortaleza tras seis segundos sin combate. Los Leones solares encabezan cargas rápidas; el fuego a distancia concentrado vence a sus escasos números.",
                "Workers gather one extra wood per operation. Grove Guardians regenerate slowly out of battle but struggle to pursue ranged enemies.",
                "Los trabajadores recolectan una madera más por ciclo. Los Guardianes de la arboleda se regeneran despacio fuera de combate, pero les cuesta perseguir a enemigos a distancia.",
                "Melee strikes restore two health to the attacker. War Trolls regenerate after combat; kiting and concentrated arrows deny sustain.",
                "Los golpes cuerpo a cuerpo devuelven dos de salud al atacante. Los Troles de guerra se regeneran tras el combate; hostigarlos a distancia y concentrar flechas les impide recuperarse.",
                "Workers gather one extra metal and carry one extra resource, and creatures gain one armor. Ember Drakes deliver ranged fire, but high food and metal costs constrain army size.",
                "Los trabajadores recolectan un metal más y cargan un recurso más, y las criaturas ganan un punto de armadura. Los Dracos de ascuas lanzan fuego a distancia, pero su alto coste en comida y metal limita el ejército.");

            P(t,
                "Bronze Tide", "Marea de bronce", "Patinated coastal roofs and warm bronze details.", "Tejados costeros con pátina y cálidos detalles de bronce.",
                "Imperial Sand", "Arena imperial", "Sun-warmed sandstone and turquoise ornament.", "Arenisca caldeada por el sol y ornamentos turquesa.",
                "Luminous Citadel", "Ciudadela luminosa", "Ivory stone and gilded fantasy fortifications.", "Piedra marfil y fortificaciones fantásticas doradas.",
                "Sapphire Drake", "Draco zafiro", "Frost-blue scales and pale luminous ridges.", "Escamas azul hielo y crestas pálidas y luminosas.",
                "Ember Crown", "Corona de ascuas", "Burnished scales with glowing amber ornament.", "Escamas bruñidas con adornos de ámbar incandescente.",
                "Storm Drake", "Draco de tormenta", "Violet storm scales and silver highlights.", "Escamas violeta de tormenta con reflejos plateados.",
                "Void Drake", "Draco del vacío", "Obsidian-violet scales with amethyst accents.", "Escamas de obsidiana violácea con toques de amatista.",
                "Oasis Regent", "Regente del oasis", "Ceremonial sandstone and turquoise elephant armor.", "Armadura ceremonial de elefante en arenisca y turquesa.",
                "Frost Troll", "Trol de escarcha", "Sapphire armor and icy pale skin accents.", "Armadura zafiro y piel pálida y helada.",
                "Bloom Guardian", "Guardián florido", "Spring-green bark and rose-colored canopy accents.", "Corteza verde primavera y copa con toques rosados.",
                "Golden Dawn", "Alba dorada", "Ivory sun lion with golden ceremonial armor.", "León solar marfil con armadura ceremonial dorada.",
                "Tidebound Guard", "Guardia de la marea", "Bronze armor and sea-colored northern cloth.", "Armadura de bronce y tela norteña del color del mar.",
                "Mountain Guard", "Guerrero de la Montaña", "A braided red-bearded dwarf in riveted leather and dark steel. Dresses the Drakeforged Reedguard.", "Un enano de barba roja trenzada, con cuero remachado y acero oscuro. Viste al Lancero de los Clanes Forjadracos.",
                "Forest Archer", "Arquero del Bosque", "A fair-haired elf in a leaf-embroidered green cloak. Dresses the Verdant Stringwarden.", "Un elfo de pelo claro con capa verde bordada de hojas. Viste al Arquero de la Alianza Verdeante.",
                "Wandering Ranger", "Explorador Errante", "A weathered ranger in a grey-green cloak with bedroll and canteen. Dresses the Skeld Reedguard.", "Un explorador curtido con capa gris verdosa, petate y cantimplora. Viste al Lancero de los Clanes de Skeld.");
        }

        // Messages the rules return when an order is rejected.
        private static void Rules(TextTranslator t)
        {
            T(t,
                "Requires faction: {f}.", "Requiere la facción {f}.",
                "Requires era: {e}.", "Requiere la era: {e}.",
                "Requires technology: {x}.", "Requiere la tecnología {x}.",
                "A completed {b} belonging to you is required.", "Necesitas este edificio terminado: {b}.",
                "This unit belongs to the {r} realm.", "Esta unidad pertenece al ámbito {r}.",
                "{u}: limit {n:int} alive or in training per player.", "{u}: límite de {n} en juego o en entrenamiento por jugador.",
                "Order rejected: {m}", "Orden rechazada: {m}");
            P(t, "historical", "histórico", "fantasy", "de fantasía",
                "Order accepted.", "Orden aceptada.", "Player does not exist.", "El jugador no existe.",
                "Select at least one armed unit.", "Selecciona al menos una unidad armada.",
                "Selection exceeds the command limit.", "La selección supera el límite de la orden.",
                "Selection contains a duplicate unit.", "La selección contiene una unidad repetida.",
                "A selected unit is no longer alive.", "Una unidad seleccionada ya no sigue con vida.",
                "You do not own every selected unit.", "No todas las unidades seleccionadas son tuyas.",
                "A selected unit cannot attack during its faction action.", "Una unidad seleccionada no puede atacar durante su acción de facción.",
                "Every selected unit must have an attack.", "Todas las unidades seleccionadas deben poder atacar.",
                "The attack target is not currently visible.", "El objetivo del ataque no está visible ahora mismo.",
                "Attack target is no longer alive or cannot be attacked.", "El objetivo ya no existe o no se puede atacar.",
                "Friendly entities cannot be attacked.", "No puedes atacar a los tuyos.",
                "Archers or soldiers on the same wall deck can attack elevated defenders.", "Solo los arqueros o los soldados del mismo adarve pueden atacar a defensores en altura.",
                "Every attacker needs a reachable firing position.", "Cada atacante necesita una posición de tiro alcanzable.",
                "Building definition does not exist.", "Ese edificio no existe.", "Entity ID space is exhausted.", "Se han agotado los identificadores de entidad.",
                "Not enough resources to build.", "No hay recursos suficientes para construir.",
                "Population capacity would exceed supported bounds.", "La capacidad de población superaría el límite admitido.",
                "Building footprint must align to the grid and fit inside the map.", "El edificio debe ajustarse a la cuadrícula y caber en el mapa.",
                "Building footprint overlaps terrain, a resource, or another building.", "El edificio se solapa con el terreno, un recurso u otro edificio.",
                "A unit occupies the building footprint or its clearance.", "Una unidad ocupa el espacio del edificio o su margen.",
                "Every builder must be able to reach the new foundation.", "Todos los constructores deben poder llegar a los nuevos cimientos.",
                "Building does not exist.", "El edificio no existe.", "You do not own this building.", "Este edificio no es tuyo.",
                "Building is already complete.", "El edificio ya está terminado.",
                "Every builder must be able to reach the foundation.", "Todos los constructores deben poder llegar a los cimientos.",
                "Only walls and gates can be turned.", "Solo las murallas y las puertas se pueden girar.",
                "A wall run holds between one and 64 stretches.", "Una muralla de corrido lleva entre 1 y 64 tramos.",
                "Only walls are laid in runs.", "Solo las murallas se trazan de corrido.",
                "This stretch overlaps another stretch of the wall.", "Este tramo se solapa con otro tramo de la muralla.",
                "Not enough resources for this stretch of the wall.", "No hay recursos suficientes para este tramo de la muralla.",
                "No builder can reach this stretch of the wall.", "Ningún constructor puede llegar a este tramo de la muralla.",
                "Every builder must be able to reach the wall.", "Todos los constructores deben poder llegar a la muralla.",
                "Drop-off building does not exist.", "El punto de entrega no existe.", "You do not own this drop-off.", "Este punto de entrega no es tuyo.",
                "A completed resource drop-off is required.", "Hace falta un punto de entrega terminado.",
                "Every carrying worker must be able to reach this drop-off.", "Todos los trabajadores con carga deben poder llegar a este punto de entrega.",
                "Every carrying worker needs a reachable completed drop-off belonging to you.", "Cada trabajador con carga necesita un punto de entrega tuyo, terminado y alcanzable.",
                "The selected workers have no cargo to deliver.", "Los trabajadores seleccionados no llevan carga.",
                "Resource node does not exist.", "El recurso no existe.", "Resource node is depleted.", "El recurso está agotado.",
                "Every worker must be able to reach the resource.", "Todos los trabajadores deben poder llegar al recurso.",
                "A reachable completed drop-off belonging to you is required.", "Hace falta un punto de entrega tuyo, terminado y alcanzable.",
                "No faction action was supplied.", "No se indicó ninguna acción de facción.", "Unsupported faction action.", "Acción de facción no admitida.",
                "This action belongs to the other faction.", "Esta acción es de la otra facción.",
                "Construction must finish first.", "Primero debe terminar la construcción.", "This outpost is relocating.", "Este puesto se está trasladando.",
                "Unit does not exist.", "La unidad no existe.", "You do not own this unit.", "Esta unidad no es tuya.",
                "Choose Logistics or Muster.", "Elige Logística o Reclutamiento.",
                "This building does not support charters.", "Este edificio no admite cédulas.",
                "Charter changes require an idle producer.", "Para cambiar de cédula, el edificio no puede estar produciendo.",
                "This charter is already active.", "Esta cédula ya está activa.",
                "Not enough resources to change charter.", "No hay recursos suficientes para cambiar de cédula.",
                "Only a Threadkeeper can establish a relay.", "Solo un Enlace puede establecer un relevo.",
                "This Threadkeeper is already deployed.", "Este Enlace ya está desplegado.", "The relay is recovering.", "El relevo se está recuperando.",
                "An active chartered Storeyard is required.", "Hace falta un Almacén con cédula activa.",
                "Move within this Storeyard's charter radius.", "Entra en el radio de la cédula de este Almacén.",
                "This building cannot relocate.", "Este edificio no se puede trasladar.",
                "Finish research, training, or charter work before packing.", "Termina la investigación, el entrenamiento o la cédula antes de empaquetar.",
                "Only a packed outpost can deploy.", "Solo un puesto empaquetado puede desplegarse.",
                "Stop the transport before deploying.", "Detén el transporte antes de desplegar.",
                "Deployment must align to the grid and fit inside the map.", "El despliegue debe ajustarse a la cuadrícula y caber en el mapa.",
                "Move the transport adjacent to the planned footprint.", "Acerca el transporte al espacio previsto.",
                "Deployment overlaps terrain, resources, or another building.", "El despliegue se solapa con el terreno, recursos u otro edificio.",
                "A unit occupies the deployment footprint or clearance.", "Una unidad ocupa el espacio del despliegue o su margen.",
                "Select at least one Ashrunner.", "Selecciona al menos un Corredor de ceniza.",
                "Every selected unit must support reposition.", "Todas las unidades seleccionadas deben poder reposicionarse.",
                "Reposition is already active.", "El reposicionamiento ya está activo.", "Reposition is recovering.", "El reposicionamiento se está recuperando.",
                "The complete placement footprint must currently be visible.", "Todo el espacio del edificio debe estar visible.",
                "Every selected unit must be able to reach the destination.", "Todas las unidades seleccionadas deben poder llegar al destino.",
                "The selection needs more free destination space.", "La selección necesita más espacio libre en el destino.",
                "Movement formation is invalid.", "La formación no es válida.", "Destination is outside the map.", "El destino está fuera del mapa.",
                "Destination is occupied by terrain, a building, or resources.", "El destino está ocupado por terreno, un edificio o recursos.",
                "A selected unit is committed to deployment.", "Una unidad seleccionada está ocupada en un despliegue.",
                "Destination does not leave enough static clearance.", "El destino no deja espacio libre suficiente.",
                "Destination cannot be reached.", "No se puede llegar al destino.",
                "The match has ended.", "La partida ha terminado.", "Only a participant may surrender.", "Solo un participante puede rendirse.",
                "Unit definition does not exist.", "Esa unidad no existe.", "This building cannot train that unit.", "Este edificio no puede entrenar esa unidad.",
                "Training must wait until this building's research finishes.", "El entrenamiento debe esperar a que termine la investigación de este edificio.",
                "Training must wait until the charter change finishes.", "El entrenamiento debe esperar a que termine el cambio de cédula.",
                "Production queue is full.", "La cola de producción está llena.", "More completed housing is required.", "Necesitas más casas terminadas.",
                "Not enough resources to train.", "No hay recursos suficientes para entrenar.",
                "This building does not produce units.", "Este edificio no produce unidades.",
                "Rally point is outside the map.", "El punto de reunión está fuera del mapa.", "Rally point is blocked.", "El punto de reunión está bloqueado.",
                "Rally point is unreachable from this building.", "No se llega al punto de reunión desde este edificio.",
                "This building is relocating.", "Este edificio se está trasladando.",
                "No research command was supplied.", "No se indicó ninguna investigación.",
                "Research building does not exist.", "El edificio de investigación no existe.",
                "You do not own this research building.", "Este edificio de investigación no es tuyo.",
                "Construction must finish before research.", "La construcción debe terminar antes de investigar.",
                "Research must wait until relocation or charter work finishes.", "La investigación debe esperar a que termine el traslado o la cédula.",
                "Technology does not exist.", "La tecnología no existe.", "This building cannot research that technology.", "Este edificio no puede investigar esa tecnología.",
                "Technology is already completed.", "Esa tecnología ya está completada.",
                "This technology or another era advancement is already in progress.", "Esta tecnología u otro avance de era ya está en curso.",
                "Research requires a building with no research or training in progress.", "Para investigar, el edificio no puede tener investigación ni entrenamiento en curso.",
                "Only the immediately following era can be researched.", "Solo se puede investigar la era siguiente.",
                "Not enough resources to research.", "No hay recursos suficientes para investigar.",
                "Unknown siege order.", "Orden de asedio desconocida.",
                "Select between one and 32 infantry or ranged soldiers.", "Selecciona entre 1 y 32 soldados de infantería o a distancia.",
                "Duplicate selected unit.", "Unidad seleccionada repetida.", "Selected unit no longer exists.", "La unidad seleccionada ya no existe.",
                "Wall decks admit infantry and archers; mounted armies and creatures remain on the ground.", "Los adarves admiten infantería y arqueros; la caballería y las criaturas se quedan en tierra.",
                "Finish the current deployment first.", "Termina primero el despliegue actual.", "Wall no longer exists.", "La muralla ya no existe.",
                "Board a completed wall segment.", "Sube a un tramo de muralla terminado.", "Scout this wall first.", "Explora primero esta muralla.",
                "The wall deck has insufficient free positions.", "El adarve no tiene suficientes huecos libres.",
                "Bring your siege ladder or tower beside the enemy wall.", "Acerca tu escalera o torre de asedio a la muralla enemiga.",
                "A selected unit is already on a wall or climbing.", "Una unidad seleccionada ya está en la muralla o escalando.",
                "Move soldiers beside the wall before climbing.", "Acerca los soldados a la muralla antes de escalar.",
                "Every selected unit must occupy a wall deck.", "Todas las unidades seleccionadas deben estar en un adarve.",
                "Choose ground immediately beside the wall.", "Elige terreno justo al lado de la muralla.",
                "No clear ground is available beside that wall.", "No hay terreno libre junto a esa muralla.",
                "Choose a clear landing beside the wall.", "Elige un punto de bajada libre junto a la muralla.",
                "Another obstacle blocks this descent.", "Otro obstáculo bloquea este descenso.",
                "Gate no longer exists.", "La puerta ya no existe.", "You do not own this gate.", "Esta puerta no es tuya.",
                "Choose a completed gate.", "Elige una puerta terminada.", "Clear the gate before closing it.", "Despeja la puerta antes de cerrarla.",
                "Pirates recruit treasure seekers as their workers.", "Los Piratas reclutan buscadoras de tesoros como trabajadoras.",
                "The network connection is unavailable.", "La conexión de red no está disponible.", "No command was supplied.", "No se indicó ninguna orden.",
                "Player IDs must be positive.", "Los identificadores de jugador deben ser positivos.",
                "This world is a drill, not an offline match.", "Esto es un entrenamiento, no una partida sin conexión.",
                "Scout this resource before ordering workers to gather.", "Explora este recurso antes de mandar a recolectar.",
                "Unsupported command type.", "Tipo de orden no admitido.", "Select at least one unit.", "Selecciona al menos una unidad.",
                "A selected unit does not exist.", "Una unidad seleccionada no existe.", "Select at least one worker.", "Selecciona al menos un trabajador.",
                "Selection contains a duplicate worker.", "La selección contiene un trabajador repetido.",
                "A selected worker does not exist.", "Un trabajador seleccionado no existe.",
                "You do not own every selected worker.", "No todos los trabajadores seleccionados son tuyos.",
                "This order requires workers.", "Esta orden necesita trabajadores.",
                "Wait for the server connection before issuing orders.", "Espera a conectar con el servidor antes de dar órdenes.",
                "Order queue full. Wait for the server.", "Cola de órdenes llena. Espera al servidor.");
        }

        // Feedback after orders from the HUD, the map and faction actions.
        private static void Commands(TextTranslator t)
        {
            T(t,
                "{f} drill. Train your unique unit at the Muster Hall; select infrastructure for faction actions.", "Entrenamiento de {f}. Entrena tu unidad única en el Cuartel; selecciona tus edificios para las acciones de facción.",
                "Gathering {r}. Resources count when delivered.", "Recolectando {r:lower}. Los recursos cuentan al entregarlos.",
                "{k} source: {n:int}. Select a Tender to gather.", "{k}: quedan {n}. Selecciona un Aldeano para recolectar.",
                "Moving in {f} formation.", "En marcha en formación {f:lower}.",
                "{f} formation selected. Tap open ground to place it.", "Formación {f:lower} elegida. Toca terreno libre para colocarla.",
                "Tap a location to preview {b}, then Confirm.", "Toca un lugar para ver {b} y luego pulsa Confirmar.",
                "{c} charter change started. Its benefit pauses during preparation.", "Cambio a la cédula de {c:lower} iniciado. Su efecto se pausa durante la preparación.",
                "{u} queued.", "{u} en cola.",
                "{b} selected.", "Selección: {b}.",
                "Selection filtered to {n:int} creatures.", "Selección filtrada: {n} criaturas.",
                "Selection filtered to {n:int} siege engines.", "Selección filtrada: {n} máquinas de asedio.",
                "Selection filtered to {n:int} cavalry.", "Selección filtrada: {n} de caballería.",
                "Selection filtered to {n:int} ranged units.", "Selección filtrada: {n} unidades a distancia.",
                "Selection filtered to {n:int} infantry.", "Selección filtrada: {n} de infantería.",
                "Group {a:int} cleared.", "Grupo {a} vaciado.",
                "Group {a:int} is empty.", "El grupo {a} está vacío.",
                "Group {a:int} set: {b:int} units.", "Grupo {a} asignado: {b} unidades.",
                "Group {a:int} set: {b:int} unit.", "Grupo {a} asignado: {b} unidad.",
                "Group {a:int} selected: {b:int} units.", "Grupo {a} seleccionado: {b} unidades.",
                "Group {a:int} selected: {b:int} unit.", "Grupo {a} seleccionado: {b} unidad.",
                "Wall ordered: {n:int} stretches. Workers build them one after another.", "Muralla encargada: {n} tramos. Los trabajadores los levantan uno tras otro.");
            P(t,
                "Select a Tender and tap a resource source to gather.", "Selecciona un Aldeano y toca un recurso para recolectar.",
                "Select your blue army and tap a red unit to attack. Spears counter cavalry; cavalry counters archers; archers counter spears.",
                "Selecciona tu ejército azul y toca una unidad roja para atacar. Las lanzas vencen a la caballería; la caballería, a los arqueros; los arqueros, a las lanzas.",
                "Similar visible units selected.", "Unidades visibles similares seleccionadas.",
                "Tap a resource to gather, or open ground to move.", "Toca un recurso para recolectar o terreno libre para moverte.",
                "Tap an enemy to attack, or open ground to move.", "Toca un enemigo para atacar o terreno libre para moverte.",
                "Workers assigned to construction.", "Trabajadores asignados a la obra.",
                "Order sent. Waiting for the server.", "Orden enviada. Esperando al servidor.",
                "Select an armed unit to attack.", "Selecciona una unidad armada para atacar.",
                "Attacking. Tap open ground to disengage, or Stop to hold fire.", "Atacando. Toca terreno libre para retirarte o Detener para dejar de disparar.",
                "Stopped. Military units hold fire until a new order.", "Detenidas. Las unidades militares no disparan hasta nueva orden.",
                "Visible army selected. Tap an enemy to attack.", "Ejército visible seleccionado. Toca un enemigo para atacar.",
                "Choose an available faction.", "Elige una facción disponible.", "Selection cleared.", "Selección borrada.",
                "Camera on your base.", "Cámara en tu base.",
                "Camera rotated. Drag the terrain to pan; pinch or scroll to zoom.", "Cámara girada. Arrastra el terreno para desplazarte; pellizca o usa la rueda para acercar.",
                "Camera follows the moving group.", "La cámara sigue al grupo en movimiento.", "Camera is free to pan.", "La cámara se desplaza libremente.",
                "Delivery order sent. Waiting for the server.", "Orden de entrega enviada. Esperando al servidor.",
                "Delivering carried resources, then waiting for orders.", "Entregando la carga; después esperarán órdenes.",
                "Select a Tender to construct a building.", "Selecciona un Aldeano para construir.", "Unknown building.", "Edificio desconocido.",
                "Valid location. Confirm to spend resources and start construction.", "Lugar válido. Confirma para gastar los recursos y empezar la obra.",
                "Build order sent. Waiting for the server.", "Orden de construcción enviada. Esperando al servidor.",
                "Foundation placed. Workers are constructing.", "Cimientos colocados. Los trabajadores están construyendo.",
                "Placement cancelled.", "Colocación cancelada.",
                "Training order sent. Waiting for the server.", "Orden de entrenamiento enviada. Esperando al servidor.",
                "Tap open ground for this building's rally point.", "Toca terreno libre para fijar el punto de reunión.",
                "Rally point set.", "Punto de reunión fijado.", "Free", "Gratis",
                "Faction order sent. Waiting for the server.", "Orden de facción enviada. Esperando al servidor.",
                "Packing supply outpost. Drop-off is offline; the transport can be attacked.", "Empaquetando el puesto de suministros. No admite entregas y el transporte puede ser atacado.",
                "Reposition active. Move to safety; Ashrunners cannot attack during the burst.", "Reposicionamiento activo. Ponte a salvo; los Corredores de ceniza no pueden atacar durante el impulso.",
                "Select one Threadkeeper near an owned chartered Storeyard.", "Selecciona un Enlace cerca de un Almacén tuyo con cédula.",
                "Relay unavailable. Move near an active owned chartered Storeyard and wait for cooldown.", "Relevo no disponible. Acércate a un Almacén tuyo con cédula activa y espera a que se recupere.",
                "Threadkeeper relay deployed. It stays exposed and stationary until the supply window ends.", "Relevo del Enlace desplegado. Queda inmóvil y expuesto hasta que acabe el suministro.",
                "Select a packed supply outpost.", "Selecciona un puesto de suministros empaquetado.",
                "Tap a clear footprint beside the stationary transport, then Confirm deploy. Move the transport there first.", "Toca un espacio libre junto al transporte detenido y pulsa Confirmar despliegue. Lleva antes el transporte allí.",
                "Clear adjacent footprint. Confirm deploy to begin preparation.", "Espacio contiguo libre. Confirma el despliegue para empezar la preparación.",
                "Deploying. The transport remains vulnerable; obstructed completion waits for clearance.", "Desplegando. El transporte sigue siendo vulnerable; si hay obstáculos, espera a que se despeje.",
                "Tap a wall near the selected infantry. Enemy walls need your ladder or siege tower beside them.", "Toca una muralla cerca de la infantería seleccionada. Para las murallas enemigas necesitas tu escalera o torre de asedio al lado.",
                "Tap clear ground beside the occupied wall to descend.", "Toca terreno libre junto a la muralla ocupada para bajar.",
                "Descent order issued.", "Orden de descenso dada.", "Tap a completed wall segment.", "Toca un tramo de muralla terminado.",
                "Wall boarding started. Protect the climbing infantry.", "Subida a la muralla iniciada. Protege a la infantería que escala.",
                "Gate order issued.", "Orden de puerta dada.",
                "Drag to draw the wall; click to fix each corner. Right-click or Confirm wall builds it.",
                "Arrastra para trazar la muralla; haz clic para fijar cada esquina. Clic derecho o Confirmar muralla para construirla.",
                "Wall ordered: 1 stretch. Workers are constructing.", "Muralla encargada: 1 tramo. Los trabajadores están construyendo.",
                "Wall order sent. Waiting for the server.", "Orden de muralla enviada. Esperando al servidor.",
                "Gate turned north-south.", "Puerta girada de norte a sur.", "Gate turned east-west.", "Puerta girada de este a oeste.",
                "Scout the crossing, build an army and destroy every enemy Hearth. Gather Food and Wood to begin.", "Explora el vado, forma un ejército y destruye todos los Hogares enemigos. Recolecta comida y madera para empezar.",
                "Capture two of three beacons with military units. Keep a majority for eight minutes; contesting interrupts the clock.", "Captura dos de los tres faros con unidades militares. Mantén la mayoría durante ocho minutos; si te los disputan, el reloj se detiene.",
                "Select mode: tap your units or drag a group. Turn Select off to give orders.", "Modo selección: toca tus unidades o arrastra para elegir un grupo. Desactívalo para dar órdenes.",
                "Command mode: tap to order; drag with a finger to pan. Two fingers pan and zoom.", "Modo órdenes: toca para ordenar y arrastra con el dedo para desplazarte. Con dos dedos, desplaza y acerca.");
        }

        // Faction cards, faction details in the HUD and faction action buttons.
        private static void Factions(TextTranslator t)
        {
            T(t,
                "Cavalry moves {p:num}% faster. Tenders carry {n:int} extra resources.", "La caballería se mueve un {p} % más rápido. Los Aldeanos cargan {n} recursos más.",
                "Cavalry moves {p:num}% faster. Tenders carry {n:int} extra resource.", "La caballería se mueve un {p} % más rápido. Los Aldeanos cargan {n} recurso más.",
                "Cavalry moves {p:num}% faster.", "La caballería se mueve un {p} % más rápido.",
                "Tenders carry {n:int} extra resources.", "Los Aldeanos cargan {n} recursos más.",
                "Tenders carry {n:int} extra resource.", "Los Aldeanos cargan {n} recurso más.",
                "Pay {c} and wait {s:num}s. Logistics adds {n:int} nearby carry; Muster speeds nearby training by {p:num}%. Switching pauses the benefit.",
                "Paga {c} y espera {s} s. Logística añade {n} de carga cerca; Reclutamiento acelera el entrenamiento cercano un {p} %. Cambiar pausa el efecto.",
                "{n:int} population.", "{n} de población.",
                "Play {f}", "Jugar con {f}",
                "Deploying {s:num}s", "Desplegando {s} s",
                "Relay cooldown {s:num}s", "Recuperación del relevo {s} s",
                "Reposition cooldown {s:num}s", "Recuperación del reposicionamiento {s} s",
                "Reposition {s:num}s", "Reposicionamiento {s} s",
                "Packing {s:num}s", "Empaquetando {s} s",
                "linked Storeyard #{id:int}", "Almacén vinculado #{id}",
                "Changing to {c}", "Cambiando a {c}",
                "Charter: {c}", "Cédula: {c}");
            P(t,
                "CHOOSE YOUR FACTION", "ELIGE TU FACCIÓN", "Next faction pair ›", "Siguientes facciones ›",
                "BALANCED / INFRASTRUCTURE", "EQUILIBRIO / INFRAESTRUCTURA", "MOBILE / FRONTIER PRESSURE", "MOVILIDAD / PRESIÓN FRONTERIZA",
                "STOREYARD CHARTERS", "CÉDULAS DEL ALMACÉN",
                "Train a support unit and deploy a temporary, stationary relay beside a chartered Storeyard. Protect it from raids.",
                "Entrena una unidad de apoyo y despliega un relevo temporal e inmóvil junto a un Almacén con cédula. Protégelo de las incursiones.",
                "Kingdom research extends charter reach.", "Una investigación de la era del Reino amplía el alcance de la cédula.",
                "MARCH RELOCATION", "TRASLADO DE LA MARCA",
                "Build a Supply Outpost. Pack, move its vulnerable transport, then deploy beside clear terrain. Drop-off stops during relocation; damage carries over.",
                "Construye un Puesto de suministros. Empaquétalo, mueve su vulnerable transporte y despliégalo junto a terreno despejado. No admite entregas durante el traslado y conserva el daño.",
                "Train a cavalry specialist. Reposition grants a brief speed burst with no attacking, followed by cooldown. Prepared spears still counter it.",
                "Entrena a un especialista de caballería. Reposicionar da un breve impulso de velocidad sin atacar, seguido de una recuperación. Las lanzas preparadas siguen venciéndolo.",
                "Kingdom research shortens packing and deployment.", "Una investigación de la era del Reino acorta el empaquetado y el despliegue.",
                "SIGNATURE ARMY", "EJÉRCITO EMBLEMÁTICO", "UNIQUE RESEARCH", "INVESTIGACIÓN ÚNICA",
                "NETWORKS & LOGISTICS", "REDES Y LOGÍSTICA", "MOBILITY & PRESSURE", "MOVILIDAD Y PRESIÓN",
                "OASIS & WAR ELEPHANTS", "OASIS Y ELEFANTES DE GUERRA", "ENDURANCE & INFANTRY", "RESISTENCIA E INFANTERÍA",
                "DISCIPLINE & SUN LIONS", "DISCIPLINA Y LEONES SOLARES", "ARCHERY & LIVING GROVES", "ARQUERÍA Y ARBOLEDAS VIVAS",
                "ATTRITION & WAR TROLLS", "DESGASTE Y TROLES DE GUERRA", "FORGES & DRAGONS", "FORJAS Y DRAGONES",
                "Link Storeyard charters and Threadkeeper relays to supply a growing kingdom.", "Enlaza cédulas de Almacén y relevos de Enlace para abastecer un reino en crecimiento.",
                "Relocate Supply Outposts and strike exposed positions with swift Ashrunners.", "Traslada Puestos de suministros y golpea posiciones expuestas con rápidos Corredores de ceniza.",
                "Build an oasis economy and support powerful, costly giant war elephants.", "Crea una economía de oasis y mantén poderosos y caros elefantes de guerra gigantes.",
                "Hold the frontier with resilient Frostguards and disciplined northern infantry.", "Defiende la frontera con resistentes Guardias de escarcha y disciplinada infantería norteña.",
                "Lead a disciplined host alongside armored sun lions and luminous citadels.", "Dirige una hueste disciplinada junto a leones solares acorazados y ciudadelas luminosas.",
                "Support woodland archers with living Grove Guardians. Protect your ranged line.", "Apoya a los arqueros del bosque con Guardianes de la arboleda vivos. Protege tu línea a distancia.",
                "Break the enemy line with brutal war trolls and relentless close-range pressure.", "Rompe la línea enemiga con brutales troles de guerra y una presión incesante cuerpo a cuerpo.",
                "Invest in mighty Ember Drakes. Their strength demands an expensive economy.", "Invierte en poderosos Dracos de ascuas. Su fuerza exige una economía cara.",
                "Support", "Apoyo", "Stationary relay", "Relevo inmóvil",
                "blocked completion waits", "si hay obstáculos, espera", "drop-off offline", "entregas desactivadas",
                "Move to clear terrain, then Deploy beside the transport. Drop-off is offline.", "Muévete a terreno despejado y despliega junto al transporte. No admite entregas.",
                "Deploy near an active owned Storeyard to extend its charter. Unarmed and exposed.", "Despliégalo cerca de un Almacén tuyo con cédula activa para ampliarla. Va desarmado y expuesto.",
                "no attacks", "sin atacar", "charter benefit offline", "efecto de la cédula en pausa", "Charter: None", "Cédula: ninguna",
                "benefits do not stack", "los efectos no se acumulan", "packing disables drop-off", "empaquetar desactiva las entregas",
                "damage persists through relocation", "el daño se conserva en el traslado",
                "Logistics charter", "Cédula de logística", "Muster charter", "Cédula de reclutamiento", "Pack outpost", "Empaquetar puesto",
                "Drop-off pauses", "Se pausan las entregas", "Reposition Ashrunners", "Reposicionar Corredores", "Move faster; no attacks", "Más rápido; sin atacar",
                "Deploy outpost", "Desplegar puesto", "Beside transport", "Junto al transporte", "Deploy relay", "Desplegar relevo",
                "Near chartered Storeyard", "Cerca de un Almacén con cédula", "Reposition", "Reposicionar");
        }

        private static void Research(TextTranslator t)
        {
            T(t,
                "{x} started at {b} #{id:int}. Training there is occupied.", "Investigación iniciada: {x}, en {b} #{id}. Su entrenamiento queda ocupado.",
                "{x} complete. Era {n:int} · {e}.", "Investigación completada: {x:list}. Era {n} · {e}.",
                "Ready at {b} #{id:int}", "Lista en {b} #{id}",
                "Build a {b}", "Construye: {b}",
                "completed {b}", "{b} (terminado)",
                "{n:int} s left", "quedan {n} s",
                "Food {a:int}     Wood {b:int}     Metal {c:int}     Stone {d:int}     ·     Shared with army and construction",
                "Comida {a}     Madera {b}     Metal {c}     Piedra {d}     ·     Compartidos con el ejército y la construcción",
                "Research: {x}", "Investigación: {x}");
            t.Rule(@"^(?<n>\d+)  (?<e>\S.*)$", (m, translate) => m.Groups["n"].Value + "  " + translate(m.Groups["e"].Value));
            P(t,
                "Research occupies its building. Training there must finish first.", "La investigación ocupa su edificio. Antes debe terminar el entrenamiento que haya allí.",
                "Research order sent. Waiting for the server.", "Orden de investigación enviada. Esperando al servidor.",
                "Completed", "Completada", "Researching", "Investigando", "Advance Era", "Avanzar de era", "Locked", "Bloqueada",
                "Scroll to see the full tree. Match continues while browsing; destroying a research site loses its unfinished investment.",
                "Desplázate para ver el árbol completo. La partida sigue mientras lo consultas; si destruyen un edificio de investigación, se pierde lo invertido sin terminar.");
        }

        // Ships, docks and the orders that carry troops across the water.
        private static void Naval(TextTranslator t)
        {
            T(t,
                "Ships x{n:int}", "Barcos x{n}",
                "Selection filtered to {n:int} ships.", "Selección reducida a {n} barcos.",
                "{a:int}/{b:int} aboard", "{a}/{b} a bordo",
                "The ship has room for {n:int} more troops.", "Al barco le caben {n} tropas más.");
            P(t,
                "Galley", "Galera", "Galleys", "Galeras", "Pirate Sloop", "Balandra pirata", "Pirate Sloops", "Balandras piratas",
                "English Frigate", "Fragata inglesa", "English Frigates", "Fragatas inglesas", "Spanish Galleon", "Galeón español", "Spanish Galleons", "Galeones españoles",
                "Dock", "Muelle", "Docks", "Muelles", "Ship", "Barco", "Naval", "Barcos",
                "Board ship", "Embarcar", "Tap one of your ships", "Toca uno de tus barcos",
                "Land troops", "Desembarcar", "Tap the shore", "Toca la orilla", "Cancel ship order", "Cancelar orden naval",
                "Sail and shell the shore", "Navegan y cañonean la costa",
                "Sailing to land them", "Navegando para desembarcarlas", "Climbing aboard", "Subiendo a bordo", "Heading for the ship", "Rumbo al barco",
                "Tap one of your ships. It must lie alongside a shore the troops can reach.", "Toca uno de tus barcos. Debe estar junto a una orilla a la que lleguen las tropas.",
                "Tap open shore ground. The ship sails beside it and lands its troops.", "Toca una orilla despejada. El barco navega hasta ella y desembarca a sus tropas.",
                "Tap one of your ships.", "Toca uno de tus barcos.",
                "Troops heading aboard.", "Las tropas van a embarcar.",
                "Sailing to land the troops.", "Navegando para desembarcar a las tropas.",
                "Select a ship with troops aboard.", "Selecciona un barco con tropas a bordo.",
                "Select the troops to embark.", "Selecciona las tropas que embarcan.",
                "A ship takes at most 32 troops.", "Un barco lleva como mucho 32 tropas.",
                "The ship no longer exists.", "El barco ya no existe.",
                "Troops board only your own ships.", "Las tropas solo embarcan en tus propios barcos.",
                "This ship carries no troops.", "Este barco no transporta tropas.",
                "Only land units board a ship.", "Solo las unidades de tierra embarcan.",
                "Leave the wall before boarding a ship.", "Baja de la muralla antes de embarcar.",
                "Bring the ship alongside a shore the troops can reach.", "Acerca el barco a una orilla a la que lleguen las tropas.",
                "You do not own this ship.", "Este barco no es tuyo.",
                "The ship carries no troops to land.", "El barco no lleva tropas que desembarcar.",
                "Choose ground inside the map.", "Elige terreno dentro del mapa.",
                "Choose open shore ground to land on.", "Elige una orilla despejada donde desembarcar.",
                "The ship cannot reach water beside that ground.", "El barco no puede llegar al agua junto a ese terreno.",
                "Ships sail only on open water.", "Los barcos solo navegan por aguas abiertas.",
                "A dock must stand on the shore, beside open water.", "El muelle debe estar en la orilla, junto a aguas abiertas.",
                "Only ranged attacks reach a ship.", "Solo los ataques a distancia alcanzan a un barco.",
                "Pirates sail their own sloops instead of the galley.", "Los piratas navegan en sus balandras, no en la galera.",
                "This navy sails its own warship instead of the galley.", "Esta marina navega en su propio buque de guerra, no en la galera.");
        }

        // Tactical HUD: action bar, context buttons, selection details, resources and objective strip.
        private static void Hud(TextTranslator t)
        {
            T(t,
                "WORKERS  {w:int}  ·  {i:int} idle       ARMY  {a:int}       PRODUCING  {b:int}/{p:int}       ORDERS/MIN  {o}",
                "TRABAJADORES  {w}  ·  {i} ociosos       EJÉRCITO  {a}       PRODUCIENDO  {b}/{p}       ÓRDENES/MIN  {o:raw}",
                "Food {a:int}     Wood {b:int}     Metal {c:int}     Stone {d:int}     People {u:int}+{r:int}/{p:int}",
                "Comida {a}     Madera {b}     Metal {c}     Piedra {d}     Población {u}+{r}/{p}",
                "Train {u}", "Entrenar {u}",
                "Requires {e}", "Requiere {e}",
                "Infantry x{n:int}", "Infantería x{n}", "Ranged x{n:int}", "A distancia x{n}", "Cavalry x{n:int}", "Caballería x{n}",
                "Creatures x{n:int}", "Criaturas x{n}", "Siege x{n:int}", "Asedio x{n}",
                "{n:int} selected", "{n} seleccionados",
                "Attacking #{n:int}", "Atacando #{n}",
                "{h:int}/{m:int} health", "{h}/{m} de salud",
                "Attack {n:int}", "Ataque {n}", "Armor {n:int}", "Armadura {n}", "Range {x:num}m", "Alcance {x} m",
                "Bonus against {x:list}", "Bonificación contra {x:list}",
                "gathers {g:int} per work cycle", "recolecta {g} por ciclo", "carry {c:int}", "carga {c}",
                "carrying {n:int} {k}", "lleva {n} de {k:lower}",
                "Climbing {s:num}s", "Escalando {s} s",
                "Constructing {p:int}%", "En construcción {p} %",
                "{u} {s:num}s at current rate", "{u}: {s} s al ritmo actual",
                "{q:int} queued", "{q} en cola",
                "tick {n:int}", "tic {n}", "simulation {x} ms", "simulación {x} ms", "{e:int} entities", "{e} entidades",
                "FRAME p95 {x} ms", "FOTOGRAMA p95 {x} ms", "RULES p95 {x} ms", "REGLAS p95 {x} ms",
                "NET {n}/MIN", "NETO {n}/MIN", "{n:int} IN TRAINING", "{n} EN ENTRENAMIENTO", "{n:int} IDLE WORKERS", "{n} OCIOSOS",
                "Capture {p:int}%", "Captura {p} %",
                "You {a:int}", "Tú {a}", "Contested {n:int}", "Disputados {n}", "Hold clock  {r:raw}", "Reloj de control  {r:raw}",
                "AFK: issue an order within {s:int}s to avoid forfeit.", "Inactividad: da una orden en {s} s para no perder por abandono.",
                "{n:int} units", "{n} unidades",
                "{n:int} stretches", "{n} tramos", "{n:int} need more resources", "faltan recursos para {n}", "{n:int} blocked", "{n} bloqueados");
            P(t,
                "Workers", "Aldeanos", "Army", "Ejército", "Stop", "Detener", "Select: off", "Selección: no", "Select: ON", "Selección: SÍ",
                "Formation", "Formación", "Clear", "Limpiar", "Home", "Base", "Rotate view", "Girar vista", "Play", "Jugar", "Online", "En línea",
                "Economy", "Economía", "Battle", "Batalla", "Factions", "Facciones", "Restart", "Reiniciar", "Menu", "Menú", "Settings", "Ajustes",
                "Research", "Investigación", "Confirm", "Confirmar", "Cancel", "Cancelar",
                "Run orders", "Ejecutar órdenes", "Next scenario", "Siguiente escenario", "Follow / Pan", "Seguir / Desplazar", "Frame army", "Encuadrar ejército",
                "Reset", "Restablecer", "Manual orders change the fixture.", "Las órdenes manuales cambian la prueba.",
                "Cancel wall order", "Cancelar muralla", "Confirm deploy", "Confirmar despliegue", "Cancel deploy", "Cancelar despliegue",
                "Confirm placement", "Confirmar colocación", "Cancel placement", "Cancelar colocación", "Cancel rally", "Quitar punto de reunión",
                "Set rally", "Punto de reunión", "Research tree", "Árbol tecnológico", "Deliver cargo", "Entregar carga",
                "More buildings", "Más edificios", "Fortifications & beasts", "Fortificaciones y bestias", "Economy & army", "Economía y ejército",
                "Close combat", "Cuerpo a cuerpo", "Keep your distance", "Mantén la distancia", "Strong against archers", "Fuerte contra arqueros",
                "Support with an escort", "Apóyalo con escolta", "Break or scale defenses", "Rompe o escala defensas",
                "Close gate", "Cerrar puerta", "Clear the doorway first", "Despeja antes el paso", "Open gate", "Abrir puerta", "Allows passage", "Permite el paso",
                "Wall garrison", "Guarnición de muralla", "Select nearby infantry", "Selecciona la infantería cercana",
                "Board / assault wall", "Subir / asaltar muralla", "Infantry and archers", "Infantería y arqueros",
                "Descend wall", "Bajar de la muralla", "Choose nearby ground", "Elige terreno cercano",
                "Confirm wall", "Confirmar muralla", "Undo corner", "Deshacer esquina", "Cancel wall", "Cancelar muralla", "Rotate gate", "Girar puerta",
                "1 stretch", "1 tramo", "1 blocked", "1 bloqueado", "Enclosure closed", "Cerco cerrado", "No stretch can be built here", "Aquí no cabe ningún tramo",
                "Battle practice", "Práctica de batalla",
                "Your army awaits. Select a unit to give an order.", "Tu ejército espera. Selecciona una unidad para darle una orden.",
                "Your settlement awaits. Select a Tender to gather and build.", "Tu asentamiento espera. Selecciona un Aldeano para recolectar y construir.",
                "tap an enemy to attack, or open ground to move", "toca un enemigo para atacar o terreno libre para moverte",
                "Command your settlement", "Dirige tu asentamiento",
                "gather resources, scout the crossing and protect your Hearth.", "recolecta recursos, explora el vado y protege tu Hogar.",
                "the online match continues while menus are open.", "la partida en línea sigue mientras los menús están abiertos.",
                "Holding fire", "Alto el fuego", "On wall deck", "En el adarve", "Ready", "Operativo", "training occupied", "entrenamiento ocupado",
                "No attack bonus", "Sin bonificación de ataque",
                "COMBAT PRACTICE", "PRÁCTICA DE COMBATE", "FACTION PRACTICE", "PRÁCTICA DE FACCIÓN", "SETTLEMENT PRACTICE", "PRÁCTICA DE ASENTAMIENTO",
                "MAP", "MAPA", "tap to look", "toca para mirar", "right-click to move", "clic derecho para mover", "hold to move", "mantén para mover",
                "YOURS", "TUYO", "CONTESTED", "DISPUTADO", "Beacon", "Faro", "BEACONS", "FAROS",
                "Scout, build an army and destroy every enemy Hearth. Protect yours.", "Explora, forma un ejército y destruye todos los Hogares enemigos. Protege los tuyos.");
        }

        // Main menu, skirmish setup and the offline match menu.
        private static void Menus(TextTranslator t)
        {
            T(t,
                "BEGIN {r} BATTLE  ›", "COMENZAR BATALLA: {r:upper}  ›",
                "{r} REALM", "ÁMBITO: {r:upper}",
                "✓  {x}", "✓  {x}",
                "Rival: {d}", "Rival: {d}",
                "{a:int} of {b:int} passed", "{a} de {b} superados",
                "Every exercise passed. You have the whole vocabulary now; the rest is deciding when to use it.",
                "Todos los ejercicios superados. Ya tienes el vocabulario entero; lo demás es decidir cuándo usarlo.",
                "YOU ARE READY    ·    PLAY A SKIRMISH    ›", "YA ESTÁS LISTO    ·    JUEGA UNA ESCARAMUZA    ›",
                "BEGIN    {n:int} min", "EMPEZAR    {n} min",
                "{n:int} enemies left", "quedan {n} enemigos",
                "CHALLENGE  ·  {x}", "DESAFÍO  ·  {x}",
                "Complete. {x} is done.", "Superado. {x} está hecho.",
                "Out of time. Open the menu to try it again.", "Se acabó el tiempo. Abre el menú para volver a intentarlo.",
                "Result: {r}", "Resultado: {r}",
                "Duration: {c:raw}", "Duración: {c:raw}",
                "Your settlement: Era {n:int}", "Tu asentamiento: era {n}",
                "Rival settlement: Era {n:int}", "Asentamiento rival: era {n}",
                "{n:int} Tenders", "{n} aldeanos",
                "{n:int} military units remaining", "{n} unidades militares restantes",
                "{n:int} buildings", "{n} edificios",
                "Stock: {s}", "Existencias: {s}",
                "{x} (legado)", "{x} (legado)");
            P(t,
                "TRAIN", "ENTRENAR", "CHALLENGES", "DESAFÍOS",
                "Short exercises", "Ejercicios cortos",
                "One thing to do, one clock. Learn a skill on its own before an opponent makes you use it under pressure.",
                "Una sola cosa que hacer y un reloj. Aprende cada destreza por separado antes de que un rival te obligue a usarla con prisa.",
                "THE TRAINING GROUND     /     FIVE SHORT EXERCISES", "EL CAMPO DE ENTRENAMIENTO     /     CINCO EJERCICIOS CORTOS",
                "Not attempted yet", "Sin intentar", "Passed", "Superado", "Not completed yet", "Aún sin superar", "In progress", "En curso",
                "Built", "Construido", "Not built yet", "Aún sin construir", "Field cleared", "Campo despejado",
                "Challenge complete.", "Desafío superado.", "Challenge failed. Try it again.", "Desafío no superado. Vuelve a intentarlo.",
                "First harvest", "Primera cosecha",
                "Hold 400 food at once. Resources only count once a Tender carries them back to a drop-off.",
                "Ten 400 de comida a la vez. Los recursos solo cuentan cuando un Aldeano los lleva a un punto de entrega.",
                "The metal seam", "La veta de metal",
                "Metal lies further out than food and wood. Scout for a seam, then keep Tenders on it and a Storeyard near it.",
                "El metal está más lejos que la comida y la madera. Explora hasta encontrar una veta, mantén Aldeanos en ella y un Almacén cerca.",
                "Raise a hall", "Levanta un cuartel",
                "Gather the wood for a Muster Hall and finish it. More Tenders on the frame raise it faster.",
                "Reúne la madera para un Cuartel y termínalo. Cuantos más Aldeanos en la obra, antes se levanta.",
                "Muster six", "Reúne seis",
                "Field six military units at once. Houses raise the population limit; the Muster Hall trains the army.",
                "Ten seis unidades militares a la vez. Las Casas suben el límite de población; el Cuartel entrena al ejército.",
                "The counter triangle", "El triángulo de contras",
                "Defeat the red army. Spears beat cavalry, cavalry beats archers, archers beat spears. Send the right unit.",
                "Derrota al ejército rojo. Las lanzas vencen a la caballería, la caballería a los arqueros y los arqueros a las lanzas. Manda la unidad adecuada.",
                "HOME", "INICIO", "STORE", "TIENDA", "EXIT GAME", "SALIR DEL JUEGO", "LANGUAGE: ES", "IDIOMA: ES", "LANGUAGE: EN", "IDIOMA: EN",
                "A NEW AGE OF STRATEGY", "UNA NUEVA ERA DE ESTRATEGIA", "Every empire\nstarts with you.", "Todo imperio\nempieza contigo.",
                "Raise a kingdom. Command creatures and siege.", "Levanta un reino. Dirige criaturas y asedios.",
                "Choose your world. Claim your frontier.", "Elige tu mundo. Conquista tu frontera.",
                "RESUME YOUR SKIRMISH    ›", "REANUDAR ESCARAMUZA    ›", "PLAY A SKIRMISH    ›", "JUGAR UNA ESCARAMUZA    ›",
                "MULTIPLAYER", "MULTIJUGADOR", "LEARN TO PLAY", "APRENDER A JUGAR", "EXPLORE THE FRONTIER", "EXPLORA LA FRONTERA",
                "Realms & Frontiers", "Reinos y fronteras", "TWELVE FACTIONS. FOUR BATTLEFIELDS.", "DOCE FACCIONES. CUATRO CAMPOS DE BATALLA.",
                "The Quartermaster", "El Intendente", "APPEARANCE ONLY", "SOLO APARIENCIA",
                "Easy rival: a small economy that only attacks from the last Era.", "Rival fácil: una economía pequeña que solo ataca en la última era.",
                "Hard rival: a larger economy, quicker reactions and three halls; attacks from minute six.", "Rival difícil: una economía mayor, reacciones más rápidas y tres cuarteles; ataca desde el minuto seis.",
                "Normal rival: attacks with a formed army from minute seven, once it has advanced an Era.", "Rival normal: ataca con un ejército formado desde el minuto siete, tras avanzar una era.",
                "CONQUEST / Destroy Hearths", "CONQUISTA / Destruye Hogares", "DOMINION / Hold beacons", "DOMINIO / Controla faros", "RIVAL AI", "IA RIVAL",
                "Equal starts. Build your army and destroy every completed rival Hearth.", "Inicios iguales. Forma tu ejército y destruye todos los Hogares rivales terminados.",
                "Hold two of three beacons for eight uninterrupted minutes.", "Controla dos de los tres faros durante ocho minutos seguidos.",
                "Return to map", "Volver al mapa", "Sound: ON", "Sonido: SÍ", "Sound: OFF", "Sonido: NO", "A full offline 1v1", "Un 1 contra 1 completo sin conexión",
                "Start match", "Empezar partida", "Resume match", "Reanudar partida", "Play again", "Jugar de nuevo", "Surrender...", "Rendirse...",
                "Confirm surrender", "Confirmar rendición", "Practice sandbox", "Práctica libre", "Main menu", "Menú principal",
                "Save match", "Guardar partida", "Load match", "Cargar partida",
                "CONTINUE SAVED MATCH", "CONTINUAR PARTIDA",
                "Match saved.", "Partida guardada.", "Saved match restored.", "Partida restaurada.",
                "There is no saved match to restore.", "No hay ninguna partida guardada.",
                "The match could not be saved.", "No se ha podido guardar la partida.",
                "This match ran too long to save.", "La partida es demasiado larga para guardarla.",
                "Only a match in progress can be saved.", "Solo se puede guardar una partida en curso.",
                "Restoring the saved match…", "Restaurando la partida guardada…",
                "MATCH DRAWN", "EMPATE", "VICTORY", "VICTORIA", "DEFEAT", "DERROTA", "MATCH PAUSED", "PARTIDA EN PAUSA",
                "Choose your faction and victory condition", "Elige tu facción y la condición de victoria",
                "Your offline match is paused.", "Tu partida sin conexión está en pausa.",
                "Scout with a Tender or mounted unit. Build a Muster Hall, train an army and protect your Hearth. Research spends the same resources as production.",
                "Explora con un Aldeano o una unidad montada. Construye un Cuartel, entrena un ejército y protege tu Hogar. Investigar gasta los mismos recursos que producir.",
                "Drag the left button to select a group, and hold shift to add to it. Pan with the arrow keys, the screen edge, the middle button or two fingers.",
                "Arrastra con el botón izquierdo para seleccionar un grupo, y mantén Mayúsculas para sumar a la selección. Desplaza la vista con las flechas, el borde de la pantalla, el botón central o dos dedos.",
                "Equal starts. Unexplored territory. A rival that gathers, builds, scouts and fights using the same rules.",
                "Inicios iguales. Territorio inexplorado. Un rival que recolecta, construye, explora y lucha con las mismas reglas.",
                "Conquest: destroy every enemy Hearth.", "Conquista: destruye todos los Hogares enemigos.",
                "Dominion: hold two of three beacons for eight uninterrupted minutes. An enemy presence contests a beacon and can reset the victory clock.",
                "Dominio: controla dos de los tres faros durante ocho minutos seguidos. La presencia enemiga disputa un faro y puede reiniciar el reloj de victoria.",
                "Conquest / destroy the Hearths", "Conquista / destruye los Hogares", "Dominion / hold the beacons", "Dominio / controla los faros",
                "For your next match: scout before choosing your army, keep workers gathering and check the objective clock. The result is final; restarting creates a fresh world.",
                "Para la próxima partida: explora antes de elegir tu ejército, mantén a los trabajadores recolectando y vigila el reloj del objetivo. El resultado es definitivo; reiniciar crea un mundo nuevo.");
        }

        // The Settings screens of the main menu and the match.
        private static void Settings(TextTranslator t)
        {
            T(t, "Volume: {n:int}%", "Volumen: {n} %", "Music: {n:int}%", "Música: {n} %", "Stored events: {a:int} / {b:int}", "Eventos guardados: {a} / {b}");
            P(t,
                "Make yourself at home", "Hazlo a tu manera",
                "Sound, controls, voice and accessibility. Saved on this device.", "Sonido, controles, voz y accesibilidad. Se guardan en este equipo.",
                "Sound", "Sonido", "Volume", "Volumen", "Music", "Música", "Music: OFF", "Música: NO",
                "CAMERA PAN", "DESPLAZAMIENTO DE CÁMARA", "CAMERA ZOOM", "ZOOM DE CÁMARA",
                "DRAG TOLERANCE", "TOLERANCIA DE ARRASTRE", "TEXT CONTRAST", "CONTRASTE DE TEXTO", "VOICE CONTROL", "CONTROL POR VOZ", "VOICE LANGUAGE", "IDIOMA DE VOZ",
                "FRAME RATE", "LÍMITE DE FPS", "Display rate", "Frecuencia de pantalla", "Unlimited", "Sin límite",
                "On", "Activado", "Off", "Desactivado", "High", "Alto", "Standard", "Estándar",
                "Push-to-talk (V)", "Pulsar para hablar (V)", "Always listening", "Escucha continua", "English", "Inglés", "Auto", "Automático",
                "GUIDE & LOCAL REPORTS", "GUÍA E INFORMES LOCALES", "PERFORMANCE ON", "RENDIMIENTO: SÍ", "PERFORMANCE OFF", "RENDIMIENTO: NO",
                "SETTINGS & GUIDE", "AJUSTES Y GUÍA", "Return", "Volver", "Controls", "Controles", "Guide", "Guía", "Local reports", "Informes locales",
                "Tune the camera, touch and voice controls to your preference. Control and a digit stores the selected group, the digit alone brings it back, and pressing it twice takes the camera there; Home returns to your base. Voice starts off and uses Windows speech recognition on this device. Changes apply immediately; gameplay rules stay the same.",
                "Ajusta la cámara, el control táctil y la voz a tu gusto. Control y un número guardan el grupo seleccionado, el número por sí solo lo recupera y pulsarlo dos veces lleva la cámara hasta él; la tecla Inicio vuelve a tu base. La voz empieza desactivada y usa el reconocimiento de voz de Windows de este equipo. Los cambios se aplican al instante; las reglas del juego no cambian.",
                "Restore defaults", "Restablecer valores", "Open guide", "Abrir guía", "Start again", "Empezar de nuevo", "Resume guide", "Reanudar guía",
                "Pause guide", "Pausar guía", "Back to controls", "Volver a controles",
                "Optional reports stay on this device. They contain event categories, dates, match ticks and counts. They exclude account details, identifiers, log messages and stack traces. Nothing is uploaded. Disabling deletes local reports and exports.",
                "Los informes opcionales se quedan en este equipo. Contienen categorías de eventos, fechas, tics de partida y recuentos. No incluyen datos de cuenta, identificadores, mensajes del registro ni trazas. No se envía nada. Desactivarlos borra los informes y exportaciones locales.",
                "Local reports: ON", "Informes locales: SÍ", "Local reports: OFF", "Informes locales: NO", "Delete reports", "Borrar informes",
                "Export report", "Exportar informe", "Open report folder", "Abrir carpeta del informe",
                "Camera pan: Slow", "Desplazamiento de cámara: lento", "Camera pan: Normal", "Desplazamiento de cámara: normal", "Camera pan: Fast", "Desplazamiento de cámara: rápido",
                "Camera zoom: Slow", "Zoom de cámara: lento", "Camera zoom: Normal", "Zoom de cámara: normal", "Camera zoom: Fast", "Zoom de cámara: rápido",
                "Drag tolerance: Low", "Tolerancia de arrastre: baja", "Drag tolerance: Normal", "Tolerancia de arrastre: normal", "Drag tolerance: High", "Tolerancia de arrastre: alta",
                "Text contrast: HIGH", "Contraste de texto: ALTO", "Text contrast: STANDARD", "Contraste de texto: ESTÁNDAR",
                "Performance overlay: ON", "Datos de rendimiento: SÍ", "Performance overlay: OFF", "Datos de rendimiento: NO",
                "Voice: Off", "Voz: desactivada", "Voice: Push-to-talk (V)", "Voz: pulsar para hablar (V)", "Voice: Always listening", "Voz: escucha continua",
                "Voice language: Español", "Idioma de voz: español", "Voice language: English", "Idioma de voz: inglés",
                "Voice language: Auto · Español", "Idioma de voz: automático · español", "Voice language: Auto · English", "Idioma de voz: automático · inglés",
                "Language: Spanish (Spain)", "Idioma: español (España)", "Language: English", "Idioma: inglés",
                "An interrupted session means the game did not close normally. It is not proof of a crash. You choose whether to share an exported file.",
                "Una sesión interrumpida significa que el juego no se cerró con normalidad; no demuestra un fallo. Tú decides si compartes un archivo exportado.",
                "Changes are saved on this device.", "Los cambios se guardan en este equipo.",
                "Changes apply now, but could not be saved on this device.", "Los cambios se aplican ya, pero no se pudieron guardar en este equipo.",
                "Local reports enabled. Nothing is sent automatically.", "Informes locales activados. No se envía nada automáticamente.",
                "Local reports disabled; stored reports and the export were deleted.", "Informes locales desactivados; se borraron los informes guardados y la exportación.",
                "The device could not save this change. Local collection stays off if consent could not be saved.", "El equipo no pudo guardar el cambio. La recogida local sigue desactivada si no se pudo guardar el consentimiento.",
                "Local reports and the previous export were deleted.", "Se borraron los informes locales y la exportación anterior.",
                "Some local report files could not be deleted.", "No se pudieron borrar algunos archivos de informes locales.",
                "Report saved on this device. Use Open report folder to find diagnostics-export.json.", "Informe guardado en este equipo. Usa Abrir carpeta del informe para encontrar diagnostics-export.json.",
                "The report could not be saved on this device.", "No se pudo guardar el informe en este equipo.",
                "Enable local reports before exporting.", "Activa los informes locales antes de exportar.", "Export a local report first.", "Exporta antes un informe local.",
                "The exported report is selected in the file browser.", "El informe exportado está seleccionado en el explorador de archivos.",
                "The file browser could not be opened. The local export is still saved.", "No se pudo abrir el explorador de archivos. La exportación local sigue guardada.",
                "The report is saved in the game's local data folder. Sharing from this device is not available in this build.", "El informe está en la carpeta de datos locales del juego. Esta versión no permite compartirlo desde este equipo.",
                "Defaults restored. Tutorial progress and local reports were cleared.", "Valores restablecidos. Se borraron el progreso de la guía y los informes locales.",
                "Defaults restored for this session; some local files could not be updated.", "Valores restablecidos para esta sesión; algunos archivos locales no se pudieron actualizar.");
        }

        private static void Guide(TextTranslator t)
        {
            T(t, "LEARN BY PLAYING / {n:int} OF 9 COMPLETE", "APRENDE JUGANDO / {n} DE 9 COMPLETADOS", "GUIDE  {n:int}/9  ·  {s}", "GUÍA  {n}/9  ·  {s:upper}",
                "Restoring the saved match… {n:int}%", "Restaurando la partida guardada… {n} %");
            P(t,
                "Camera", "Cámara", "Selection", "Selección", "Movement", "Movimiento", "Delivery", "Entrega", "Building", "Construcción",
                "Training", "Entrenamiento", "Attack", "Ataque", "Victory", "Victoria", "Complete", "Completada",
                "GUIDE COMPLETE / 9 OF 9", "GUÍA COMPLETADA / 9 DE 9",
                "The guide is available in Practice and offline AI matches.", "La guía está disponible en la práctica y en las partidas sin conexión contra la IA.",
                "The guide follows your actions. You can stop or restart it from Settings.", "La guía sigue lo que haces. Puedes pararla o reiniciarla desde Ajustes.",
                "Guide paused. Resume keeps completed steps; Start again clears them.", "Guía en pausa. Reanudar conserva los pasos completados; Empezar de nuevo los borra.",
                "The guide is available in Practice and offline AI matches. Your completed steps are saved. Leave this match and return to Practice to continue learning; online play continues while Settings is open.",
                "La guía está disponible en la práctica y en las partidas sin conexión contra la IA. Tus pasos completados se guardan. Sal de esta partida y vuelve a la práctica para seguir aprendiendo; la partida en línea continúa mientras Ajustes está abierto.",
                "Start in Practice to learn camera movement, selection, gathering, building, training, combat and Era progression. Then win a real AI match. The guide remembers completed steps across matches and can be paused any time.",
                "Empieza en la práctica para aprender la cámara, la selección, la recolección, la construcción, el entrenamiento, el combate y el avance de era. Después gana una partida de verdad contra la IA. La guía recuerda los pasos completados entre partidas y puedes pausarla cuando quieras.",
                "Explore the map: pan with the arrow keys, the screen edge or a finger drag. Pinch or use the mouse wheel to zoom.",
                "Explora el mapa: desplázate con las flechas, el borde de la pantalla o arrastrando con el dedo. Pellizca o usa la rueda del ratón para acercar.",
                "Tap one of your workers, or use Workers to select the workers visible on screen.",
                "Toca uno de tus aldeanos o usa Aldeanos para seleccionar los que se ven en pantalla.",
                "With a unit selected, tap open ground and watch it move. Keep Select mode off when giving orders.",
                "Con una unidad seleccionada, toca terreno libre y mira cómo se mueve. Mantén desactivado el modo Selección al dar órdenes.",
                "Select a Tender and tap Food or Wood. Wait for it to carry resources home: only a delivery adds to your stock.",
                "Selecciona un Aldeano y toca comida o madera. Espera a que lleve los recursos a casa: solo lo entregado suma a tus existencias.",
                "Select a Tender, choose Shelter or Muster Hall, tap a clear location and Confirm. Gather more Wood if needed; wait for construction.",
                "Selecciona un Aldeano, elige Casa o Cuartel, toca un lugar despejado y pulsa Confirmar. Recolecta más madera si hace falta y espera a que se construya.",
                "Select your Hearth to train a Tender, or a completed Muster Hall to train a soldier. Keep gathering and wait for the unit to appear.",
                "Selecciona tu Hogar para entrenar un Aldeano o un Cuartel terminado para entrenar un soldado. Sigue recolectando y espera a que aparezca la unidad.",
                "Select a soldier and tap a visible enemy to attack. Train at your Muster Hall if needed; scout to find the rival.",
                "Selecciona un soldado y toca un enemigo visible para atacar. Entrena en tu Cuartel si hace falta y explora para encontrar al rival.",
                "Open Research and advance to the next Era. Meet its building requirements and gather the displayed cost; let research finish.",
                "Abre Investigación y avanza a la era siguiente. Cumple sus requisitos de edificios, reúne el coste indicado y deja que termine la investigación.",
                "Open Play and start an AI match. Win Conquest by destroying every rival Hearth, or Dominion by holding two beacons for eight minutes. This guide continues there.",
                "Abre Jugar y empieza una partida contra la IA. Gana en Conquista destruyendo todos los Hogares rivales, o en Dominio controlando dos faros durante ocho minutos. La guía continúa allí.",
                "Win this match: destroy every rival Hearth in Conquest, or hold two beacons for eight uninterrupted minutes in Dominion. Protect your economy.",
                "Gana esta partida: destruye todos los Hogares rivales en Conquista o controla dos faros durante ocho minutos seguidos en Dominio. Protege tu economía.",
                "Training complete. You explored, gathered, built, trained, attacked, advanced an Era and won a match. Try the other faction or victory condition.",
                "Aprendizaje completado. Has explorado, recolectado, construido, entrenado, atacado, avanzado una era y ganado una partida. Prueba otra facción u otra condición de victoria.");
        }

        private static void Online(TextTranslator t)
        {
            T(t,
                "Server result recorded: {r}. Profile and history refreshed.", "Resultado registrado en el servidor: {r}. Perfil e historial actualizados.",
                "Waiting {n:int}s. Search widens over time.", "Esperando {n} s. La búsqueda se amplía con el tiempo.",
                "Room {c:raw}", "Sala {c:raw}", "Battlefield: {m}", "Campo de batalla: {m}", "Faction: {f}", "Facción: {f}", "Mode: {m}", "Modo: {m}",
                "Player: {p:raw}", "Jugador: {p:raw}", "{n:int} points", "{n} puntos", "{n:int} wins", "{n} victorias", "{o} vs {p:raw}", "{o} contra {p:raw}",
                "Workers {n:int}", "Trabajadores {n}", "Army {n:int}", "Ejército {n}", "Buildings {n:int}", "Edificios {n}");
            P(t,
                "Sign in to host a private match or find an opponent.", "Inicia sesión para crear una partida privada o buscar rival.",
                "Connected. The match continues while menus are open.", "Conectado. La partida sigue mientras los menús están abiertos.",
                "Server ready and game version compatible. Sign in or create an account to play.", "Servidor listo y versión compatible. Inicia sesión o crea una cuenta para jugar.",
                "Signed in. Choose a private room or matchmaking.", "Sesión iniciada. Elige una sala privada o el emparejamiento.",
                "Signed out. An active match continues until reconnection or forfeit.", "Sesión cerrada. Una partida activa sigue hasta que vuelvas a conectar o se pierda por abandono.",
                "Profile and match history refreshed.", "Perfil e historial actualizados.",
                "Sign in again to resume your session.", "Vuelve a iniciar sesión para continuar.",
                "Connection interrupted. Reconnecting; the server match continues.", "Conexión interrumpida. Reconectando; la partida del servidor continúa.",
                "Match finished. The server has recorded the result.", "Partida terminada. El servidor ha registrado el resultado.",
                "Reconnected to the current server state.", "Reconectado al estado actual del servidor.",
                "The server match is no longer active. Return to the lobby; history shows recorded results.", "La partida del servidor ya no está activa. Vuelve a la sala; el historial muestra los resultados registrados.",
                "Order accepted by the server.", "Orden aceptada por el servidor.", "The server rejected the order.", "El servidor rechazó la orden.",
                "Order delivery could not be confirmed. Reconnecting.", "No se pudo confirmar la entrega de la orden. Reconectando.",
                "Cannot reach the local server. Start the Emberfield service on this computer, or enter your shared HTTPS server address.",
                "No se puede conectar con el servidor local. Inicia el servicio de Emberfield en este equipo o escribe la dirección HTTPS de vuestro servidor compartido.",
                "Cannot reach this HTTPS server. Check the address, connection and server availability.", "No se puede conectar con este servidor HTTPS. Revisa la dirección, la conexión y si el servidor está disponible.",
                "Username or password is incorrect.", "Usuario o contraseña incorrectos.",
                "That username is already registered. Sign in or choose another.", "Ese usuario ya está registrado. Inicia sesión o elige otro.",
                "Use a username of 3-24 letters, digits or underscores and a password of 10-128 bytes.", "Usa un usuario de 3 a 24 letras, dígitos o guiones bajos y una contraseña de 10 a 128 bytes.",
                "The game and server use different versions. Update them to the same build.", "El juego y el servidor usan versiones distintas. Actualízalos a la misma versión.",
                "Choose a supported PvP realm and battlefield.", "Elige un ámbito PvP y un campo de batalla admitidos.",
                "Real purchases are not available in this alpha. No payment was taken.", "Las compras reales no están disponibles en esta alfa. No se ha cobrado nada.",
                "This account does not own that appearance.", "Esta cuenta no tiene esa apariencia.",
                "The server has not enabled free alpha cosmetic claims.", "El servidor no ha activado los cosméticos gratuitos de la alfa.",
                "The purchase receipt could not be verified for this account and item.", "No se pudo verificar el recibo de compra para esta cuenta y este objeto.",
                "That appearance is not available in this catalog.", "Esa apariencia no está disponible en este catálogo.",
                "That room is unavailable. Check its code or create another.", "Esa sala no está disponible. Revisa el código o crea otra.",
                "Leave the current room or cancel matchmaking first.", "Sal primero de la sala actual o cancela el emparejamiento.",
                "Surrender before leaving an active match.", "Ríndete antes de salir de una partida activa.",
                "There is no active server match for this account.", "Esta cuenta no tiene ninguna partida activa en el servidor.",
                "The server is temporarily unavailable. Try again shortly.", "El servidor no está disponible ahora mismo. Inténtalo de nuevo en un momento.",
                "The server is full. Try again shortly.", "El servidor está lleno. Inténtalo de nuevo en un momento.",
                "Too many requests. Wait a moment before trying again.", "Demasiadas peticiones. Espera un momento antes de volver a intentarlo.",
                "The server could not complete this request. Refresh the lobby and try again.", "El servidor no pudo completar la petición. Actualiza la sala e inténtalo de nuevo.",
                "Sign in to play.", "Inicia sesión para jugar.", "Server address", "Dirección del servidor",
                "127.0.0.1 connects only to this computer and needs a running local server.", "127.0.0.1 solo conecta con este equipo y necesita un servidor local en marcha.",
                "To play from different computers, both players need the same HTTPS server address.", "Para jugar desde equipos distintos, los dos jugadores necesitan la misma dirección HTTPS del servidor.",
                "Check server connection", "Comprobar conexión", "Username (3-24 letters, numbers or underscore)", "Usuario (3-24 letras, números o guion bajo)",
                "Password (at least 10 characters)", "Contraseña (10 caracteres como mínimo)", "Sign in", "Iniciar sesión", "Create account", "Crear cuenta",
                "PvP realm", "Ámbito PvP", "Battlefield", "Campo de batalla", "Faction", "Facción", "Mode", "Modo",
                "Host private 1v1", "Crear 1 contra 1 privado", "Private room code", "Código de sala privada", "Join private room", "Unirse a sala privada",
                "Find casual opponent", "Buscar rival casual", "Find ranked opponent", "Buscar rival clasificatorio", "Ready to start", "Listo para empezar",
                "Leave room", "Salir de la sala", "Cancel matchmaking", "Cancelar emparejamiento", "Return to lobby", "Volver a la sala",
                "Refresh profile and history", "Actualizar perfil e historial", "Sign out", "Cerrar sesión",
                "Online matches continue in menus. Reconnect promptly after a lost connection.", "Las partidas en línea siguen con los menús abiertos. Vuelve a conectar cuanto antes si pierdes la conexión.",
                "Private matches do not change rank. Ranked results come from the server.", "Las partidas privadas no cambian el rango. Los resultados clasificatorios los da el servidor.",
                "Working...", "Procesando...", "IDLE", "EN ESPERA", "QUEUED", "EN COLA", "LOBBY", "SALA", "STARTING", "INICIANDO", "ACTIVE", "EN CURSO",
                "FINISHED", "TERMINADA", "ABORTED", "CANCELADA", "MATCH ABORTED", "PARTIDA CANCELADA",
                "ranked", "clasificatoria", "ready", "listo", "disconnected", "desconectado",
                "win", "victoria", "loss", "derrota", "draw", "empate", "aborted", "cancelada", "server_restart", "reinicio del servidor",
                "Bronze", "Bronce", "Silver", "Plata", "Gold", "Oro", "Platinum", "Platino", "Diamond", "Diamante", "Master", "Maestro", "Legend", "Leyenda");
        }

        private static void Store(TextTranslator t)
        {
            T(t,
                "{n:int} APPEARANCES", "{n} APARIENCIAS",
                "{x} preview equipped for offline play. No purchase was made.", "Prueba de {x} equipada para jugar sin conexión. No se ha hecho ninguna compra.");
            P(t,
                "Free alpha previews are for offline play. Listed prices are provisional.", "Las pruebas gratuitas de la alfa son para jugar sin conexión. Los precios son provisionales.",
                "Make your army your own. Every item changes appearance only.", "Haz tuyo tu ejército. Cada objeto solo cambia la apariencia.",
                "Architecture collection", "Colección de arquitectura", "Army appearance", "Apariencia del ejército", "Character skin", "Aspecto de personaje",
                "Offline army appearance restored.", "Apariencia del ejército sin conexión restablecida.",
                "RESET OFFLINE APPEARANCE", "RESTABLECER APARIENCIA SIN CONEXIÓN", "SYNCING…", "SINCRONIZANDO…", "SYNC ONLINE WARDROBE", "SINCRONIZAR VESTUARIO EN LÍNEA",
                "OFFLINE PREVIEW EQUIPPED", "PRUEBA SIN CONEXIÓN EQUIPADA", "TRY FREE IN OFFLINE PLAY", "PROBAR GRATIS SIN CONEXIÓN",
                "EQUIP ALPHA TEST ITEM", "EQUIPAR OBJETO DE PRUEBA ALFA", "EQUIP IN ONLINE WARDROBE", "EQUIPAR EN EL VESTUARIO EN LÍNEA", "PURCHASES OPEN SOON", "COMPRAS DISPONIBLES PRONTO",
                "Sign in through Multiplayer to sync your online wardrobe.", "Inicia sesión en Multijugador para sincronizar tu vestuario en línea.",
                "Online wardrobe synced. Offline previews do not grant paid ownership.", "Vestuario en línea sincronizado. Las pruebas sin conexión no te dan la propiedad de pago.",
                "Online appearance saved for your next room. Combat rules are unchanged.", "Apariencia en línea guardada para tu próxima sala. Las reglas de combate no cambian.");
        }

        // Lines already written in Spanish that still name English buildings or modes.
        private static void Corrections(TextTranslator t)
        {
            P(t,
                "Conquest: destruye los Hearths. Dominion: controla los faros.", "Conquista: destruye los Hogares. Dominio: controla los faros.",
                "Corsario Carmesí: selecciona terreno para moverte o un enemigo para atacar. Héroe de los Piratas; reclutable en su Hearth en Navales.",
                "Corsario Carmesí: selecciona terreno para moverte o un enemigo para atacar. Héroe de los Piratas; se recluta en su Hogar, en Navales.",
                "Tripulación pirata: sable, pistola y exploración. La buscadora recolecta y construye; recluta más en el Hearth y el Muster Hall de los Piratas, en Navales.",
                "Tripulación pirata: sable, pistola y exploración. La buscadora recolecta y construye; recluta más en el Hogar y el Cuartel de los Piratas, en Navales.",
                "ARQUERÍA & DEFENSA", "ARQUERÍA Y DEFENSA", "SABLES, PÓLVORA & EXPLORACIÓN", "SABLES, PÓLVORA Y EXPLORACIÓN");
            // Resource costs such as "50 food 20 wood".
            t.Rule(@"^(?:\d+ (?:food|wood|metal|stone)(?: |$))+$", (m, translate) =>
                Regex.Replace(m.Value, @"\b(food|wood|stone)\b", word => word.Value == "food" ? "comida" : word.Value == "wood" ? "madera" : "piedra"));
        }
    }
}
